### ISSUE TITLE
Feature-gate experimental Items

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/yewtil#17]
Not everything in this crate will be ready for people to use from the start. Newer, unfinished or unvetted items can be kept behind a feature flag, while older and more stable items will be available by default.

Feature flagging every feature might be useful as well. Given that this crate represents a hodge-podge of different ideas, it would be nice for people to be able to select exactly what they want, even excluding stable features.

Something like:
```toml
default = ["stable"]
stable = ["feature1", "feature2", "feature3", "etc..."]
experimental = ["feature4", "feature5"]

feature1 = []
# etc...
```
